### ISSUE TITLE
Anlegen von neuen Sprachvariablen

### ISSUE THREAD

**Issue by dmolineus** [bit3archive/contao-language-editor#4]
Es wäre super, wenn die Erweiterung auch Sprachvariablen anlegen kann, die noch nicht definiert sind.

Hintergrund: Bei einem Projekt ist es geplant einzelne Bereiche (Formulare usw.) mit InsertTags zu vesehen, die dann übersetzt werden. (Beispielsweise: {{t:form.contact.title}}).

**Comment by zonky2** [comment]
@dmolineus hast Du Dich ggf. mit dem Tool weiter beschäftigt? läuft das noch auf aktuellen Contao-Versionen (>= 3.5)?

**Comment by dmolineus** [comment]
There u go: http://github.com/netzmacht/contao-language-editor

**Comment by zonky2** [comment]
Danke! den Link könnte @tristanlins auf "Startseite" packen...

**Comment by tristanlins** [comment]
Hab ich gemacht.

**Comment by zonky2** [comment]
wo?!
https://github.com/bit3archive/contao-language-editor

**Comment by tristanlins** [comment]
![screenshot_20160113_111742](https://cloud.githubusercontent.com/assets/343404/12291406/4558e99a-b9e7-11e5-9518-14cefac69b0a.png)

**Comment by zonky2** [comment]
uff... unten im Text wäre das m.E. "offensichtlicher" ;-)
